version: "3.8"

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - APP_NAME=secretecho-frontend
      - V1_API_ENDPOINT=http://localhost:3001/api/v1
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
      - SESSION_COOKIE_NAME=secretecho_user_session
      - SESSION_COOKIE_PASSWORD=QbTGf8aLNqbXeRCTWgkWURXk2SuXzzQM7KL
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:3001/plugin_generator
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
